delete from CompromissoLancamento
delete from Compromisso
delete from lancamento
delete from transferencia
delete from ContaConjuntaCategoria
delete from ContaFinanceira
delete from ContaConjunta
delete from OpcaoMenuAcessos
delete from Notificacao
delete from LancamentoCategoria
delete from LoginSolicitacaoTrocaSenha
delete from Usuario